tailscale:
    key: ENC[AES256_GCM,data:IVoU9VOIXISJdJxDmBda4kbux3kkaY73NBzBcE5/lWq8ZalC3LF4550r6gS5dn3vDFE3QCKanqb+vH68Iuk=,iv:qp6+pQj7/jk7m+cgqC02rDsupTQV1Kz+dbLvODgdkUA=,tag:DxULRPSa8ZT5m0/uPdSMXA==,type:str]
users:
    alex: ENC[AES256_GCM,data:9yWs2AMLNiyTGBGSqrlFwz2uu1bLPYUKbUAdTv9r8Spn+CDZiSFjPNJlmZMUnwv2tc2mtWvcU/TFAMujUSZKudInOZsgZ26ovw==,iv:ZQZ9vipkjzZqCAbvhAfdIW+m1yZqKaRIhGxWpPIb8yI=,tag:lHr27a8GJtPxbafMfCuLmA==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0THcva0FnUmxWVUthRnl2
            ZEZLaHd5TzlBMnNwUzJZL1VFT2lIMG5tUkFJCkMvQWVqRGU0ZzVjYjlIaXpjcjFL
            V1ExbERKbC9CNUNIOUxmcnRySHRQTU0KLS0tIDhpUUZWT2k1amNrUndmd2lsY05O
            Wjgrd05zUmFOQVJHbTR5RkVCK3R0K3cK3zkIGhusFKUWwjEMx2jW6eZFlLSKTWL4
            zIEtR50ivhTLGH0VXcw44foUP/9y1w0SQGC99QVErG97AfkT93P0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsd79y9nt2z376sjavjvdg92ayk7u9x2ywh4vzm5g6tadgmwzcmqy6n6s8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWlmc0hRUTByNWt0L1FW
            anpMbllyRWxBSm1oVE44SGtUcUtBcXcvcVI4CnJqUWM4b2w3U0N1MDYxNXVXaWxV
            SHlyMkg1UnNvVTJWd2drS0hnZ2RpUUUKLS0tIFJSa1ordk4yNTRJZXNYYU9mckdv
            T1VaeUdlcDBqR0dHYzl0TDN5VmlSUG8KFFP6r882815YYPFZk8uZ4Lyi94jLy2ih
            F/9M58nIviVsbzeTaplmgGuK06YNlSd1oopqzcffZU7Ry9M73FYWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T03:25:23Z"
    mac: ENC[AES256_GCM,data:kWBnjLDudRcnQAzdg07E5pdwV4bEXK6Q2fe9J+/xKQltCP0MLKgY7YHK43k6qiSSGQ46pSWZRodGQwK2df3XGZjXirb6RIdzx4PVdTYNkcepvcSgK4Rnzge+7JhFmXGSnPI/SpmnNvQvoF8HS9ZQpRS96Jc7J0pRgYsQrjPaROw=,iv:a+EPGgQVfMjmGImqC+YK14CXOIOhflvD1P3uV2+NlOU=,tag:yjNXEZj8so0Fd+ZhvxlGRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
