acme:
    zone_api_token: ENC[AES256_GCM,data:9IXU7nyKhA/GTLoRt/fv3zws35Yd3CA05SuAu1sz3b0pFUB0l7ssRA==,iv:9+ajo7qF0OHPlcNjtnA0Jjrn6GzE870iH1+AdzCczdg=,tag:XmoGzhl12rD9vtECzumXUA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:XneEbHnFdoRnz/mNnU7iytf3qZYcuD07IZOJwlTvJ/E+2NaqcdWiag==,iv:vBPiRwpqyyjhT+69jnxx4tWudNnvGIb8XOztyoCquP8=,tag:LowFQ3LFs7jiIcIn+2C8Bg==,type:str]
authentik:
    ldap:
        token: ENC[AES256_GCM,data:HwgHv+tDo52+y2naTTkP0M9DGxpNbUUa/cQXJGc0STLOBEeGQuVdAGzgK7UmKwQoommRwLh/HIC1nNGV,iv:HkhcypThFj73+6frQWIzyNb3u2ibdSVOcHomcvcadC0=,tag:IwxXUPTW2/GD4LCUeYdeOQ==,type:str]
    proxy:
        token: ENC[AES256_GCM,data:oyepnGuE6wpNM4rgPSujmW37hOSYMiATfU93/JNkzY1yLzNlFqZwXNrRx0jUaEv6Sr06us4KRecK6+fv,iv:NAia5p59laFKrRwpvkbn5ZZYuLY27R7sBKCh+PaWq58=,tag:EQY90wth8nj0ZBMrRbIoKQ==,type:str]
backblaze:
    backups:
        id: ENC[AES256_GCM,data:FICiOkfxXm+dyhmq9JMtDRaeTo+Ek1IB+w==,iv:gpbTPWGGb+xLE2WodsQeuxzZ5yff4SekKXkmvL2TbVQ=,tag:QcTes/bj4OwdO++wkfiWgQ==,type:str]
        key: ENC[AES256_GCM,data:PcbMplMxx7HS0k+3ijGVNlrIznXSwCcUvGrlQ4OQyg==,iv:/zg0KE8jmTP/IRZ4eyi6wh6nPpK4s44z6IrPTuD9Ic4=,tag:UWRmND97qm+z80ZP5MXOgQ==,type:str]
    watch:
        id: ENC[AES256_GCM,data:GDD8UFk5eI9C3iFmQwKjZDES0B8rG5MRNw==,iv:fBv6Tej1n03uBJUtE+UhZm+bNmIC4fKrx8O0fM88R/k=,tag:0SSGST7/S6cCIGTF20IWsg==,type:str]
        key: ENC[AES256_GCM,data:z3bTZUQ+e+GCT78yVuJYe0c6eLypt2S452fRBMbRrQ==,iv:Dc0zh43d8pPMFER70hEhU/tglwQEFsB+HFyZDU64h9k=,tag:aCgCcbFYRqyQVqNuba6G/Q==,type:str]
karakeep:
    openai_key: ENC[AES256_GCM,data:HPaCGTxMdS4H8AQsycq+HN+a8TRq/93EsA0jMinEjzk9QOiPOa2krD6QyEKkGacyRmqypa+xwYNQ7zK0bQpMLL9QVUF6tMbigV8sDe82NlvLpyx7/iF9FUu5MEyqEIxnIQJxKrI7e5AbcZ210Li2xrMSENJwLPA8OmS97OHvMwtU08jQ9+5d2Qssw4RM1xO1Ne24L7amQ/4HW4CzSQk+IMkV1VIZsK4=,iv:UwSG1A7lAfaPEEGXUKkD6UsrSDwjMucrEuu1Z4l5LAE=,tag:SXHBOj7E7X7ovS5QKQD2Tg==,type:str]
    oauth:
        client_id: ENC[AES256_GCM,data:1YsmTtvzwQ4njj8h+zUQOHzeBfJn/ABcMi5ikRxyn/k8QgRNjmm30w==,iv:QM0o18TggM/usqUmVK3cXTsAC/klwNpDT5Mdz8v9Jmg=,tag:VNtkrpVuwhW4N3YKPb7O+g==,type:str]
        client_secret: ENC[AES256_GCM,data:m+56yfFkMfSEwlgywmyvkdLdUVdYaBBTWEoGmpp1YBXZ94sWxlyop5s9DexX2LtnQQzgKyRv20dl/OWDCe0XTG8V6pBL/kNPUC/kMVXSA0SD24aBHOJqkFrWgWUmfoI6iL2UWhPHy6JEBtoaNyPo0122dU4mza2Lv/sEs1DHrrM=,iv:XAoYGo7ravArl84F3FHAlU9eaLQOdHfl0wryy6nALL0=,tag:8gF1ELtaQ+kx48b58PebXQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:Q2VuTokCyw1B534y6J3NedPLf0Y=,iv:VcKjHBobev8rF0HrzHrmAPbCZeXw4SmPdTCjrqmYnQg=,tag:2udrLC79hXHMWF0J6huPdA==,type:str]
        port: ENC[AES256_GCM,data:kg/C,iv:hBIX/tCWad459IjNHUWuNkVxz21RxMlazoMlZIssQwY=,tag:EybylP5wy1aUqTxn5RRdPQ==,type:str]
        username: ENC[AES256_GCM,data:C6aFguCnqRpACou2jo6CZS0IOBHmv6YzipLPprkvT1juUim6,iv:1dA5il+0ZPiWWpk8bZ/RSNAiFWUsyY25leGfy8Owjj4=,tag:6kYIF+/jqDjQtrmXyMtWUw==,type:str]
        password: ENC[AES256_GCM,data:AGY+ZhjdmH6wz8gyI6qvC2+K2HTNXSR4OtY/nKIJ82dY6SUC,iv:QHapfEZGx8dEGYyQrE5gl7H/yA57VasYLAopxFcrm5A=,tag:cQP9U5olAIBEir6gGqgZHw==,type:str]
mealie:
    oidc_client_secret: ENC[AES256_GCM,data:BoisyhUr63aXjsylbiDzjksYzMszE/dYXOHze3cKuXVVO/oYQtackAIEcsjwsEWs9GTu92ev5fT54RLIizyofo1hDBLj0LoOBxgQxF05g0EejLB8jo1309WUvopB6n/ycB5T7PHVTag3hfMBU9/HDZTLzYlnZN14dXiKt5Yri9A=,iv:xguCJXWcx/IAwIqHdX0Qo3RZS8xjcqMKNNSd8vcAuQc=,tag:2KaNe6VZjJkj0Cu7FteDlA==,type:str]
    openai_api_key: ENC[AES256_GCM,data:2GfD+BLIA4GQt0YqclHCHW0EoEkPscedCLR+Qgc7mNzCuNm7M6iSpToBhmMROXK+w8VvSeREB8xufQIhXVie7SflnX6OTsnKSvqGdLCVW7DMJnHvoMzYBAKVutowNoX+Gh6Qkw9vbE85g7/e4KIlFYopidZXVA7sBigTf7xeA3jpy98+OEe/70b5gVAm5B0=,iv:W4gIq8wd2MwLjEF3vwIUEFPMxvFIeqyWN+86i6J4tXo=,tag:NPV6vUkpAhQBfrgnMqxKsg==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:znFRcMBmtg72HDeQ2EQon3fH7to=,iv:zydrPrQE+pXTluOpu95yLBTI21ZbJkIaudpMHH6HTy8=,tag:Dd4UG2ZJX9NdZHnbBxbKPw==,type:str]
        port: ENC[AES256_GCM,data:2/fx,iv:PGZ+x1PLDQSmEFnGF0RPSB1kd1daLoTKaYujoqZDCBI=,tag:zu702AuIyou2OnTGxdScvw==,type:str]
        username: ENC[AES256_GCM,data:+soudJpNxLQOqfJj9FHFktk4pKwK1Wdioi9HHY/UXGKtGRP7,iv:12JPNZOYQ2nzlx92T6yetNyXATSJw2CEOkjYVV9NfD4=,tag:b6+tRI4Iy1gdr3Bj6z7aQw==,type:str]
        password: ENC[AES256_GCM,data:g0te0TaJNncH0b6XVXv6vH387ZDRAgjgnsIxoQDuGMxpGTSn,iv:h+2Mkjg0nsW73OMSnDg2lUk2VsbEMozGL/8YyUu6JKI=,tag:JkDJYVieAldLJZeb86/brA==,type:str]
meilisearch:
    master_key: ENC[AES256_GCM,data:iOw+AYThFgJRw5MLPtwNXB4yffV7q9q1fKSKtU9AAGrijR/mjtRLILN6aLk=,iv:yAHb+LGltOtY63pf6r0eJ1mAZ9tVOonUSe8ojBaC2RQ=,tag:MSffwwO43HVMe2lmOniihA==,type:str]
miniflux:
    client_id: ENC[AES256_GCM,data:aiMtGyi2FAQ4vOZYDaCRbtqnft2U9Aela6GVpqhYe6JkjW30d/Kveg==,iv:qf03Aadg2ode59uQqVUYPUsHfFv/fckfKD+24MNZ/Is=,tag:v3LpunB8e2kvNLeBN2J4CA==,type:str]
    client_secret: ENC[AES256_GCM,data:9hba8fb38Lor5qJKseXzgl/tPyzmaMfWoZ5AsvkbbDxOWx7Qo1FOx2eIkgAWGH4Zqqjg2FW/P2nSOv2Veq07Wu4dhu38FyWSbHdNWO/lM2zGuiPIknSfdker/W9kHBFloo1EKmyOQB/suJlB1EfyLKR8KZrqWboOzMfjxuntTls=,iv:ysQG/t25ExjF9KQ7yOMnYE8RQqQMXHaokRzprG7ZDHA=,tag:u0ja4RsdR48Lgvciu2Xx9w==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:IVoU9VOIXISJdJxDmBda4kbux3kkaY73NBzBcE5/lWq8ZalC3LF4550r6gS5dn3vDFE3QCKanqb+vH68Iuk=,iv:qp6+pQj7/jk7m+cgqC02rDsupTQV1Kz+dbLvODgdkUA=,tag:DxULRPSa8ZT5m0/uPdSMXA==,type:str]
users:
    alex: ENC[AES256_GCM,data:9yWs2AMLNiyTGBGSqrlFwz2uu1bLPYUKbUAdTv9r8Spn+CDZiSFjPNJlmZMUnwv2tc2mtWvcU/TFAMujUSZKudInOZsgZ26ovw==,iv:ZQZ9vipkjzZqCAbvhAfdIW+m1yZqKaRIhGxWpPIb8yI=,tag:lHr27a8GJtPxbafMfCuLmA==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:v4nRLXyU,iv:mqWydeUmukIzC4cdAGhAw1JR8/norF5mQKH2dAo0128=,tag:JJ9cJ3qwp7a4/cOTx0Nd7A==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:2pG57+7pF/BV3iOdk5U1CL7RIXcMPdBdbAAb/TsPG4lrvRJC,iv:M77qzXyhaWM/7v/3gr4c1/Iiy6kH3QuXJg259NuvLtg=,tag:pv3ZwxULHLiV4CMJ0Jg5Dw==,type:str]
        installation_key: ENC[AES256_GCM,data:ipS08hWvqtT0k9v/m9nRBTdSX2Y=,iv:sduNFdrHfiSoeChNFg9jwigXHvbiJdUVMC3q++bvupc=,tag:rjCPGtvWUc9fXWuZyKmQFQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:5uc/5ne+kV71I2CQVWVvRoB2WIw=,iv:hpSa/GpdI6MlL4FJWex0n9Yya/vnEDKnrNXArEqjFY8=,tag:+5FG90FBkxpY4+HJEFiMVw==,type:str]
        port: ENC[AES256_GCM,data:FYZm,iv:AM9GOhVxAVlyNT23KAjM5SsYM7SNeQ7HwYyL/i2jH68=,tag:RwHrMH4+g6iW5fWsgvMI9g==,type:str]
        username: ENC[AES256_GCM,data:ci5GDjx/OPKvrMl7RlfbbItZGZjvj0DWC2jpTeMJ5xUenFNC,iv:SSmfK+IltCBZPAA/3zfyAje/GYESXGYmiPSzQtMegXM=,tag:jcJCbBE6tZ4gB4h/YRsnwA==,type:str]
        password: ENC[AES256_GCM,data:HNENcaeiXeFDVxTMrog6O8J7EbWhk1hBpNaMdGLFeiEpNoM7,iv:xAKitY5rOm+QUhgIeJfP7416OUnO/z3oilB93P2zL7M=,tag:Sm4Ep7Is9RNw+gy2AU7VvQ==,type:str]
vpn:
    private_key: ENC[AES256_GCM,data:7xOql/B6lfn2ROqzuYb8I6dW4qWnb52S+eB/T5zc+b4gSkJ4Q2hZBmlNHRU=,iv:5k6grX8/tCSaKKREJ2CRVIkjbsW1SUAuMTUcUsCIoek=,tag:jzwG0eGUub0HZpPWlDNLTg==,type:str]
workflows:
    encryption-key: ENC[AES256_GCM,data:tf8vWq6ni+DXQdNAy88nVFBGRiFxKRbhW2wUkn2CYbdw4XZqtw9jV3+eF3qt1FUhJcvD3+DmS2kZk2Oos7Gc+g==,iv:Dik1JrNeWzckhZUB9IsoXXLNzmiwEgHmFl0etj/Gerg=,tag:l0Qo/EjqmJPA8JAYn3S/nw==,type:str]
    oidc:
        client-id: ENC[AES256_GCM,data:CmaDmjM05BjIrYLsIg32WNBRMNAq3QbEZ7SogY1c5mGJkVjd8kv+Bg==,iv:jVBj2QPBzCyK0FdTBaLsSZXPfmlLQt0nYedQwSyNngs=,tag:zULqqPDBRWRpyV5smIXkWA==,type:str]
        client-secret: ENC[AES256_GCM,data:m49nRSn7jhzTZYPEl3OQOS8yq71rDdvZki7A/2eBzT1CRsjaNo6iWZ2HCybwTuRQCxqe5nnojKfnrAG3m6/P1k+4h3HsRgWxe1XXGhCqqpspuxGNKCdK5dsLe4PC+PGDryxhWENjaTA0GYOGl11ZxX72kdBPPLFLm2LOHh5bwz0=,iv:JJcA7AUvtA4NId8RdGgH4jK3AIylJ1/A1Yz7jX3KHaA=,tag:vOEfYt9BG3PaVjLkUfZlFQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:QGEVK8IuSppgT7uuXbIhSqs58ko=,iv:ZB4ipmhy8eMFaw5PHlrTW53Nxng9M2t4T4MhF+4G0lY=,tag:6fgf0XGvYQuix9L4hRj7sg==,type:str]
        port: ENC[AES256_GCM,data:w610,iv:SiCq+l31BE7oz32MBXXjbdUZG4iu9hy2dyOQz1I2rfg=,tag:LQ87wSNfPuI5VPC5NI7Aqw==,type:str]
        username: ENC[AES256_GCM,data:FzQxOPJVC/VOaLYQsYfaOW9g+sHc5BdLC+O5jVshFQUI2+ee,iv:9kznew7LJYnJhZKdvrFhIwR+VBDeAm2MF5FY58MrSI8=,tag:KoV1hcQvn7KYyoAJ6L9qKA==,type:str]
        password: ENC[AES256_GCM,data:qb/RRLHXMhmbMi+ibYqkBvzYV+WVyQdcAawIG4xpVl98ltC3,iv:ui5iujOii/CkjnwG5aM7w2lBoFval50S1UeR5fBHkHw=,tag:kD9XBwYQXt/VQX1RaCfK/Q==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0THcva0FnUmxWVUthRnl2
            ZEZLaHd5TzlBMnNwUzJZL1VFT2lIMG5tUkFJCkMvQWVqRGU0ZzVjYjlIaXpjcjFL
            V1ExbERKbC9CNUNIOUxmcnRySHRQTU0KLS0tIDhpUUZWT2k1amNrUndmd2lsY05O
            Wjgrd05zUmFOQVJHbTR5RkVCK3R0K3cK3zkIGhusFKUWwjEMx2jW6eZFlLSKTWL4
            zIEtR50ivhTLGH0VXcw44foUP/9y1w0SQGC99QVErG97AfkT93P0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsd79y9nt2z376sjavjvdg92ayk7u9x2ywh4vzm5g6tadgmwzcmqy6n6s8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWlmc0hRUTByNWt0L1FW
            anpMbllyRWxBSm1oVE44SGtUcUtBcXcvcVI4CnJqUWM4b2w3U0N1MDYxNXVXaWxV
            SHlyMkg1UnNvVTJWd2drS0hnZ2RpUUUKLS0tIFJSa1ordk4yNTRJZXNYYU9mckdv
            T1VaeUdlcDBqR0dHYzl0TDN5VmlSUG8KFFP6r882815YYPFZk8uZ4Lyi94jLy2ih
            F/9M58nIviVsbzeTaplmgGuK06YNlSd1oopqzcffZU7Ry9M73FYWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:03:10Z"
    mac: ENC[AES256_GCM,data:9rBJYA65HK8FbnfqvAX3/o81TTSJHSpsY1S+4jVKWN79HJ1tVuYVwIpJZz1UTiTJLUPIpNVvVbdxDPuEVA//21QQ1BMF3IOUsw4CJ43YrheVvi6+M5iANL/FYWNHGFkE6bimGqJ1c/wC4oUL4/BQXqNjop1r2m0oHWlRrS7ntAg=,iv:8ADAttGomI4xX9wTKxq3MC7n36CIiy0Im7vapzRP3x4=,tag:4wyWmW7n+X4tUizAUY8vcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
