acme:
    zone_api_token: ENC[AES256_GCM,data:9IXU7nyKhA/GTLoRt/fv3zws35Yd3CA05SuAu1sz3b0pFUB0l7ssRA==,iv:9+ajo7qF0OHPlcNjtnA0Jjrn6GzE870iH1+AdzCczdg=,tag:XmoGzhl12rD9vtECzumXUA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:XneEbHnFdoRnz/mNnU7iytf3qZYcuD07IZOJwlTvJ/E+2NaqcdWiag==,iv:vBPiRwpqyyjhT+69jnxx4tWudNnvGIb8XOztyoCquP8=,tag:LowFQ3LFs7jiIcIn+2C8Bg==,type:str]
authentik:
    ldap:
        token: ENC[AES256_GCM,data:HwgHv+tDo52+y2naTTkP0M9DGxpNbUUa/cQXJGc0STLOBEeGQuVdAGzgK7UmKwQoommRwLh/HIC1nNGV,iv:HkhcypThFj73+6frQWIzyNb3u2ibdSVOcHomcvcadC0=,tag:IwxXUPTW2/GD4LCUeYdeOQ==,type:str]
    proxy:
        token: ENC[AES256_GCM,data:oyepnGuE6wpNM4rgPSujmW37hOSYMiATfU93/JNkzY1yLzNlFqZwXNrRx0jUaEv6Sr06us4KRecK6+fv,iv:NAia5p59laFKrRwpvkbn5ZZYuLY27R7sBKCh+PaWq58=,tag:EQY90wth8nj0ZBMrRbIoKQ==,type:str]
backblaze:
    backups:
        id: ENC[AES256_GCM,data:FICiOkfxXm+dyhmq9JMtDRaeTo+Ek1IB+w==,iv:gpbTPWGGb+xLE2WodsQeuxzZ5yff4SekKXkmvL2TbVQ=,tag:QcTes/bj4OwdO++wkfiWgQ==,type:str]
        key: ENC[AES256_GCM,data:PcbMplMxx7HS0k+3ijGVNlrIznXSwCcUvGrlQ4OQyg==,iv:/zg0KE8jmTP/IRZ4eyi6wh6nPpK4s44z6IrPTuD9Ic4=,tag:UWRmND97qm+z80ZP5MXOgQ==,type:str]
    watch:
        id: ENC[AES256_GCM,data:GDD8UFk5eI9C3iFmQwKjZDES0B8rG5MRNw==,iv:fBv6Tej1n03uBJUtE+UhZm+bNmIC4fKrx8O0fM88R/k=,tag:0SSGST7/S6cCIGTF20IWsg==,type:str]
        key: ENC[AES256_GCM,data:z3bTZUQ+e+GCT78yVuJYe0c6eLypt2S452fRBMbRrQ==,iv:Dc0zh43d8pPMFER70hEhU/tglwQEFsB+HFyZDU64h9k=,tag:aCgCcbFYRqyQVqNuba6G/Q==,type:str]
meilisearch:
    master_key: ENC[AES256_GCM,data:iOw+AYThFgJRw5MLPtwNXB4yffV7q9q1fKSKtU9AAGrijR/mjtRLILN6aLk=,iv:yAHb+LGltOtY63pf6r0eJ1mAZ9tVOonUSe8ojBaC2RQ=,tag:MSffwwO43HVMe2lmOniihA==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:IVoU9VOIXISJdJxDmBda4kbux3kkaY73NBzBcE5/lWq8ZalC3LF4550r6gS5dn3vDFE3QCKanqb+vH68Iuk=,iv:qp6+pQj7/jk7m+cgqC02rDsupTQV1Kz+dbLvODgdkUA=,tag:DxULRPSa8ZT5m0/uPdSMXA==,type:str]
users:
    alex: ENC[AES256_GCM,data:9yWs2AMLNiyTGBGSqrlFwz2uu1bLPYUKbUAdTv9r8Spn+CDZiSFjPNJlmZMUnwv2tc2mtWvcU/TFAMujUSZKudInOZsgZ26ovw==,iv:ZQZ9vipkjzZqCAbvhAfdIW+m1yZqKaRIhGxWpPIb8yI=,tag:lHr27a8GJtPxbafMfCuLmA==,type:str]
vpn:
    private_key: ENC[AES256_GCM,data:K0QGr8bnuQZmMTXBowcTke9ajdHQIEHTNf2B+mJ59+LHACipnGnKaK4wuIA=,iv:98jQwKbl0hrP6vOWEuBEjZYVsPjytkvulHWKbLlw4Nk=,tag:0bC7XjQ6N4k/n9b8LCnbPg==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0THcva0FnUmxWVUthRnl2
            ZEZLaHd5TzlBMnNwUzJZL1VFT2lIMG5tUkFJCkMvQWVqRGU0ZzVjYjlIaXpjcjFL
            V1ExbERKbC9CNUNIOUxmcnRySHRQTU0KLS0tIDhpUUZWT2k1amNrUndmd2lsY05O
            Wjgrd05zUmFOQVJHbTR5RkVCK3R0K3cK3zkIGhusFKUWwjEMx2jW6eZFlLSKTWL4
            zIEtR50ivhTLGH0VXcw44foUP/9y1w0SQGC99QVErG97AfkT93P0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsd79y9nt2z376sjavjvdg92ayk7u9x2ywh4vzm5g6tadgmwzcmqy6n6s8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWlmc0hRUTByNWt0L1FW
            anpMbllyRWxBSm1oVE44SGtUcUtBcXcvcVI4CnJqUWM4b2w3U0N1MDYxNXVXaWxV
            SHlyMkg1UnNvVTJWd2drS0hnZ2RpUUUKLS0tIFJSa1ordk4yNTRJZXNYYU9mckdv
            T1VaeUdlcDBqR0dHYzl0TDN5VmlSUG8KFFP6r882815YYPFZk8uZ4Lyi94jLy2ih
            F/9M58nIviVsbzeTaplmgGuK06YNlSd1oopqzcffZU7Ry9M73FYWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T19:42:17Z"
    mac: ENC[AES256_GCM,data:+dp0kTseJv5YKO53Y/t7ws4oYof6eRrUiqoPSliYGXcjhMSGePYPFVvVNsbS2+BPl2VeASqrjXiwnGHmf6OKHcny9h15zG2wKcoW74/td7Ff0NxkrO2QAgqGatYwKWCaCzGGajIxIOYiQJxJzyuJk6pXOyrI4mfmR1QM1Zc0h2E=,iv:tAgBXrXugrmqGM/UG6uUX9iG3HQEXdEmd1UnbRAY/1I=,tag:h4WD1kLweLRHnMFZrXH5HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
