acme:
    zone_api_token: ENC[AES256_GCM,data:9IXU7nyKhA/GTLoRt/fv3zws35Yd3CA05SuAu1sz3b0pFUB0l7ssRA==,iv:9+ajo7qF0OHPlcNjtnA0Jjrn6GzE870iH1+AdzCczdg=,tag:XmoGzhl12rD9vtECzumXUA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:XneEbHnFdoRnz/mNnU7iytf3qZYcuD07IZOJwlTvJ/E+2NaqcdWiag==,iv:vBPiRwpqyyjhT+69jnxx4tWudNnvGIb8XOztyoCquP8=,tag:LowFQ3LFs7jiIcIn+2C8Bg==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:IVoU9VOIXISJdJxDmBda4kbux3kkaY73NBzBcE5/lWq8ZalC3LF4550r6gS5dn3vDFE3QCKanqb+vH68Iuk=,iv:qp6+pQj7/jk7m+cgqC02rDsupTQV1Kz+dbLvODgdkUA=,tag:DxULRPSa8ZT5m0/uPdSMXA==,type:str]
users:
    alex: ENC[AES256_GCM,data:9yWs2AMLNiyTGBGSqrlFwz2uu1bLPYUKbUAdTv9r8Spn+CDZiSFjPNJlmZMUnwv2tc2mtWvcU/TFAMujUSZKudInOZsgZ26ovw==,iv:ZQZ9vipkjzZqCAbvhAfdIW+m1yZqKaRIhGxWpPIb8yI=,tag:lHr27a8GJtPxbafMfCuLmA==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0THcva0FnUmxWVUthRnl2
            ZEZLaHd5TzlBMnNwUzJZL1VFT2lIMG5tUkFJCkMvQWVqRGU0ZzVjYjlIaXpjcjFL
            V1ExbERKbC9CNUNIOUxmcnRySHRQTU0KLS0tIDhpUUZWT2k1amNrUndmd2lsY05O
            Wjgrd05zUmFOQVJHbTR5RkVCK3R0K3cK3zkIGhusFKUWwjEMx2jW6eZFlLSKTWL4
            zIEtR50ivhTLGH0VXcw44foUP/9y1w0SQGC99QVErG97AfkT93P0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsd79y9nt2z376sjavjvdg92ayk7u9x2ywh4vzm5g6tadgmwzcmqy6n6s8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWlmc0hRUTByNWt0L1FW
            anpMbllyRWxBSm1oVE44SGtUcUtBcXcvcVI4CnJqUWM4b2w3U0N1MDYxNXVXaWxV
            SHlyMkg1UnNvVTJWd2drS0hnZ2RpUUUKLS0tIFJSa1ordk4yNTRJZXNYYU9mckdv
            T1VaeUdlcDBqR0dHYzl0TDN5VmlSUG8KFFP6r882815YYPFZk8uZ4Lyi94jLy2ih
            F/9M58nIviVsbzeTaplmgGuK06YNlSd1oopqzcffZU7Ry9M73FYWhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T07:03:51Z"
    mac: ENC[AES256_GCM,data:HRZ0e9Y5vb4QpJnJjCL7MWwIHG3mujldBaGHKfeOfQWrpkruFrlYzE4GqZ/c6R7HHPYswimWTvXueW7qRhA+XOlWgXz3cHNjkuX785ava9QmGMe6SlE4mFvCutdRKUmTGLmMZkVkC1Wc6m8cSZRnT31zjE1TJ5IoM/KK0vn4p9w=,iv:ymnwB72XXuBS8JqEW258p4BibFEr6c8QRjUtKNSmAIE=,tag:wj46qd2FfiyWv3JUWErz1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
