---
keys:
  - &personal age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
  - &github arn:aws:kms:ca-central-1:416515258441:alias/sops
  - &krantz age14ug6lkhhf6svlqskahna8fwxh9rmkz6gkmvjhd55elaalwzp7gtq37k5rr

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|yml|env)$
    key_groups:
      - age:
          - *personal

  - path_regex: secrets/github/[^/]+\.(yaml|yml|env)$
    key_groups:
      - age:
          - *personal
        kms:
          - arn: *github

  - path_regex: secrets/nix/krantz/[^/]+\.(yaml|yml|env)$
    key_groups:
      - age:
          - *personal
          - *krantz
