---
extends: default

rules:
  float-values:
    level: error
    require-numeral-before-decimal: true
  line-length: disable
  octal-values:
    level: error
    forbid-implicit-octal: true
  comments:
    level: error
    require-starting-space: true
    min-spaces-from-content: 1

  document-start:
    ignore: |
      secrets/*
