black := "poetry run black"
isort := "poetry run isort --profile black --filter-files"

# List all the tasks
list:
  @just --list --unsorted

# Install dependencies
install:
  poetry install

# Launch the development server
dev:
  poetry run flask --app applier run

# Build the project
build:
  rm -rf dist
  poetry build

# Lint the project
lint:
  poetry check
  poetry lock
  {{black}} .
  {{isort}} .

alias l := lint

# Run tests in CI
ci:
  poetry check
  poetry lock --check
  {{black}} --check --diff .
  {{isort}} --check-only --diff .

# Publish a new version
publish kind:
  #!/usr/bin/env bash

  version=$(poetry version {{kind}} -s)

  git add pyproject.toml
  git commit -m "chore(applier): bump version"
  git push

  git tag applier/v$version
  git push --tags
