# Show all the tasks
list:
  @just -lu

# Ensure the formatting is correct
format *FLAGS:
  terragrunt hclfmt {{FLAGS}}

# Run linters
lint:
  tflint --init
  tflint --recursive

# Ensure the project is valid
validate:
  terragrunt validate

# Open a console
console:
  terragrunt console

# Plan the changes
plan:
  terragrunt plan

# Apply the changes
apply:
  terragrunt apply

# Checks to run in CI
ci: (format "--terragrunt-check") lint validate

alias c := console
alias f := format
alias fmt := format
alias l := lint
alias v := validate
