testing: ENC[AES256_GCM,data:dQ/W95hPb+QXisJhfkrEHkqXvag=,iv:KoeP69SDwmQlajW08x85m4j7v2swYmiqipUXNt+CMcw=,tag:FwzWPESNjaLkRvkz+/YyyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFlaeXR1NVZsWGsvNVF6
            dU95ays2MkltWG9WRERqdTV2S1g0ejVoTkJBCnVvcEc0K2FHWUhZSFpOZFdTUlJG
            Wmw2eG51NFhuN20vRk1kVUo5YWVRWUEKLS0tIER3NkR0ZDFLbWpmMnFrbHNtTjgr
            UGhsRi9GTENjT3FWaHFlQjVSMWhNNGsK4Wpn+eUXBFwia+ovG0zJam1tHkEVHJo7
            sDEKrRiuoV9NWD0042ViGG1NWgm5ZCtZUjqaS4ufh5f//AXiF/18lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ug6lkhhf6svlqskahna8fwxh9rmkz6gkmvjhd55elaalwzp7gtq37k5rr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL21LQytkTnRmaWRjc0g0
            YWtRSXV3aTY2ejIzNFhjaVNUazdBWGJDTHlBCm5mTjNjNGh5OTMxU3NpZ0NvNHN1
            cTg1VnN2VVNtUHlEMXVHNHUza2Jud2sKLS0tIHQwdmYvUzRLT1J1a3RXb1I1b3Mv
            WDcybEU5L3RpK3pPQWhwSWN3STJiSUUKREGIiy0rYabeILe9D7EnJpiSf5NcLjIm
            J2T0SbeSnpMvP/FXsdMHJWzV/xqLjonHKZvxRjPNOqo+UqtYwrEEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T00:48:02Z"
    mac: ENC[AES256_GCM,data:qSA0uEuDFnn80BdI9Dls2NiZAGrkFQ1+UtwY0miBn0sQJFYMw/rABNE2ORrqYuFzJJxWCgE0d59wNgmPynQgOZBTOHBPHCTSpvkGu3SeBTMUl7gepvmUnNuAM6FttMgT/cCJvL+d8+W8Tvrk+P4xSeY9y3MyQrO4Rks5zHsrWC8=,iv:PW7sxOqyhHacohUDH0tfBZl1PbZl3vxZ3Q5Gy44uG3I=,tag:uSx7G4Sq7SQlhhig9LAjtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
