vaultwarden:
    push:
        installation_id: ENC[AES256_GCM,data:k8lVYzxRbbvtEesC+gWCchyMnbQkSMj4qY7et1+JjjqNw/19,iv:3Mb2IqBNhUnijTvYChWpqBXhDLY6S17bNutOmLv7BMg=,tag:th/Xgbiy6AwVOPVOA8z0Aw==,type:str]
        installation_key: ENC[AES256_GCM,data:q/4gb4/zu/q/tAzJnL1eAyHQl+U=,iv:abim1KZxr2/nwOhp4ipG7OfX+4P4bGHxhBfxBVQOX4c=,tag:QfXHYLZOwL7DLgza8Sxf3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFlaeXR1NVZsWGsvNVF6
            dU95ays2MkltWG9WRERqdTV2S1g0ejVoTkJBCnVvcEc0K2FHWUhZSFpOZFdTUlJG
            Wmw2eG51NFhuN20vRk1kVUo5YWVRWUEKLS0tIER3NkR0ZDFLbWpmMnFrbHNtTjgr
            UGhsRi9GTENjT3FWaHFlQjVSMWhNNGsK4Wpn+eUXBFwia+ovG0zJam1tHkEVHJo7
            sDEKrRiuoV9NWD0042ViGG1NWgm5ZCtZUjqaS4ufh5f//AXiF/18lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ug6lkhhf6svlqskahna8fwxh9rmkz6gkmvjhd55elaalwzp7gtq37k5rr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL21LQytkTnRmaWRjc0g0
            YWtRSXV3aTY2ejIzNFhjaVNUazdBWGJDTHlBCm5mTjNjNGh5OTMxU3NpZ0NvNHN1
            cTg1VnN2VVNtUHlEMXVHNHUza2Jud2sKLS0tIHQwdmYvUzRLT1J1a3RXb1I1b3Mv
            WDcybEU5L3RpK3pPQWhwSWN3STJiSUUKREGIiy0rYabeILe9D7EnJpiSf5NcLjIm
            J2T0SbeSnpMvP/FXsdMHJWzV/xqLjonHKZvxRjPNOqo+UqtYwrEEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T02:54:23Z"
    mac: ENC[AES256_GCM,data:tX03EVFtQwDE+u8kLZdKp3bThvG6tUH5HFjAqxwi2MEL0QCnpa/YTwpI1WxJ/ct/y0EsAsxjNmWOw4YfoXT54UclXq7REMRamn+KwtFf5ipTiyqI2VZ+jnAhtEkfuJZCld3pw//ybFeEru29dFkUF2x4soMzfpnt9L+v+e5o5e0=,iv:2PQTwZ8Y9tRPvqrOM5pWN/6k6g0QA2lyrnDTlUxYxj4=,tag:ZQp5vKKVB+v2OYpAJgPCBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
