acme:
    zone_api_token: ENC[AES256_GCM,data:Btx1akJ2gPshXdoeRTvaY58R6tqktWKJO7FIwyB86Pmgls06md2t2g==,iv:3bHck01yCqIwqJJnrVJ9Gbk5nFGsjvKfBiRGJ/CRVNA=,tag:6JRqFknYKNCBgdShmoLO9g==,type:str]
    dns_api_token: ENC[AES256_GCM,data:SWWulUuZR13qM87JXP28TMZHgJ3qx2nqEvxqUqUN156fCGSSHwX8gw==,iv:5wnTMbOpwK6oHCm++5l+S1l+Z66NPE/1L9jRbbHHGSI=,tag:4hnhXsv0D4LH3L7GMUi1qw==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:u1EH7zZFuA9G0tOBtJsmbFX8Th2U7EaDz1CEfnrhHO9bACzClhw1ZhFFkaLxQqUCUq5Ox/FP/xYxDAadiO4opBwSr16nmHvH/rYOohUjfqg+bjBbrTmzg0bF8acKrxH5ykmeEU2HCP6l74wu4r5EdaitVEPLaQ==,iv:YQgeOeW3T3/d8ChvChQIOLvkXMS1tErhPQq9UPNrwz4=,tag:8PIIaSrfy6W/CTUx3dXrYg==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:k8lVYzxRbbvtEesC+gWCchyMnbQkSMj4qY7et1+JjjqNw/19,iv:3Mb2IqBNhUnijTvYChWpqBXhDLY6S17bNutOmLv7BMg=,tag:th/Xgbiy6AwVOPVOA8z0Aw==,type:str]
        installation_key: ENC[AES256_GCM,data:q/4gb4/zu/q/tAzJnL1eAyHQl+U=,iv:abim1KZxr2/nwOhp4ipG7OfX+4P4bGHxhBfxBVQOX4c=,tag:QfXHYLZOwL7DLgza8Sxf3w==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:WIsrgVDEgCOEWjD5qKj1kGensbkn+BcUQh9IYC5iRLeENuXIiA==,iv:4WZbjVcZl1EotCmjeIhuegDir14OmqXdTUhkzSY4m3g=,tag:PKmbpOvgND0Rt537BFUGQw==,type:str]
        port: ENC[AES256_GCM,data:2K21,iv:yXOyfl040S50P8xPnfFGHlGqhOsgBxlU17Vi+XegagA=,tag:pvVYEOE/LFMTdBGKNBISIg==,type:str]
        username: ENC[AES256_GCM,data:pC4akIAmpBQ4hohN1aM4/ktQlgA=,iv:KQsJRvMHMBqe7rKa4nje/4N0ZM0g/CG8G2OmDVxEbVk=,tag:7r/32aqP+fsAkJFKhWBNkg==,type:str]
        password: ENC[AES256_GCM,data:xLlz39U2tRZD+YLf++RX/fRJwaw+8gHA2HiJaVgXeKbkx0Be2m/FDKGgCL0=,iv:3Be93Xf9Y5+dnXnmaq0VKahEIjxeIhRUxW269+pSa4w=,tag:Xn/dHE866+VVexn9IZ/ZYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFlaeXR1NVZsWGsvNVF6
            dU95ays2MkltWG9WRERqdTV2S1g0ejVoTkJBCnVvcEc0K2FHWUhZSFpOZFdTUlJG
            Wmw2eG51NFhuN20vRk1kVUo5YWVRWUEKLS0tIER3NkR0ZDFLbWpmMnFrbHNtTjgr
            UGhsRi9GTENjT3FWaHFlQjVSMWhNNGsK4Wpn+eUXBFwia+ovG0zJam1tHkEVHJo7
            sDEKrRiuoV9NWD0042ViGG1NWgm5ZCtZUjqaS4ufh5f//AXiF/18lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ug6lkhhf6svlqskahna8fwxh9rmkz6gkmvjhd55elaalwzp7gtq37k5rr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL21LQytkTnRmaWRjc0g0
            YWtRSXV3aTY2ejIzNFhjaVNUazdBWGJDTHlBCm5mTjNjNGh5OTMxU3NpZ0NvNHN1
            cTg1VnN2VVNtUHlEMXVHNHUza2Jud2sKLS0tIHQwdmYvUzRLT1J1a3RXb1I1b3Mv
            WDcybEU5L3RpK3pPQWhwSWN3STJiSUUKREGIiy0rYabeILe9D7EnJpiSf5NcLjIm
            J2T0SbeSnpMvP/FXsdMHJWzV/xqLjonHKZvxRjPNOqo+UqtYwrEEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T05:32:52Z"
    mac: ENC[AES256_GCM,data:d2dvv5uwYLyP2XfsAHNUBLh9iby3lKW8T5iRLaHjAlwbcP3JRb1P97zrhlp8l1BPVDs/UwQ0pijlBXHsIbzdPojkvt9ThvoETduFnkGH3aJJWEAWykOJgoKxNkA3ZaPhJvWjuEBkJUX6pFWfu/Gkq74GMonyQ6gJJWY5uSHMrMw=,iv:V3WgrzkXgPuuKi8yb4Q/oHMfLbiTdn8NUwn07CiNVbY=,tag:+cuB4KEk8nFQTtvdBP3rOw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
