acme:
    zone_api_token: ENC[AES256_GCM,data:Btx1akJ2gPshXdoeRTvaY58R6tqktWKJO7FIwyB86Pmgls06md2t2g==,iv:3bHck01yCqIwqJJnrVJ9Gbk5nFGsjvKfBiRGJ/CRVNA=,tag:6JRqFknYKNCBgdShmoLO9g==,type:str]
    dns_api_token: ENC[AES256_GCM,data:SWWulUuZR13qM87JXP28TMZHgJ3qx2nqEvxqUqUN156fCGSSHwX8gw==,iv:5wnTMbOpwK6oHCm++5l+S1l+Z66NPE/1L9jRbbHHGSI=,tag:4hnhXsv0D4LH3L7GMUi1qw==,type:str]
authentik:
    ldap:
        token: ENC[AES256_GCM,data:+9Xb+b4jZHMo8E0vJBKo2vd6ucMdrmQQwh4TF71hhU4bLgQfL+vdmsVO4rWqiVzKlL/B1nnhShzy/5Pg,iv:1VotXc0ho3snNJrjQzjQ5gpA2pw4Xh5eH/KuC2cNI6w=,tag:gm7C1NzpdgeFNF8pNkVIxA==,type:str]
    proxy:
        token: ENC[AES256_GCM,data:4kfGtT0VJtkPlqoT3KxfWKH5kTl3objFev/dXIQ6UCB6ncCuRxl5ZTSB31f9CgLgFQNupwaROUX8w9CG,iv:ofRmeyiKAUiyw5ys5tZLnBAv3/MfV2mGj7f/SQSXUvQ=,tag:dYK8ROhj4FlB9Hdn2kNoJg==,type:str]
backblaze:
    id: ENC[AES256_GCM,data:STJRYxbAw9vh23PAbzZk1xvIquPHMy6R+w==,iv:8mOQirpcQJGFbWRCaKIfZfgBatPR4JIjS+prcOTaffk=,tag:7dDvnu1v2ds8R5blFxOytQ==,type:str]
    key: ENC[AES256_GCM,data:PQbTfS6X1Ln6NDtBNx3A5EjRo2RrZYNHWoXa2BwZ+g==,iv:ihXmaIcPGgavtzbjXbW6NCFW0/0Q1Xu1fXqWRSKzU20=,tag:pAXCb/6fEyfHLvrVggREbg==,type:str]
mealie:
    oidc_client_secret: ENC[AES256_GCM,data:hJh+uQMkzfW3td23HaYX4ix06Z9EHTVga9SM81gmd7fXbXCljpr1Fu9nrZfMphMjSeLWd3kJvgvXcaY4rBO/V0Rha3muFqzpTRAGVFinZQKaSU5cFzHJ8kMEYlAgQN3v0evwpXljJrPGwGNsn/RcFYedNlgMt99s3udouZtq9aM=,iv:k993j8xDwQFRKWARjM0A+pVnaZ39nkBmrowvBPm9pvc=,tag:cYZKyTMuwTnMZTWwx/PkEA==,type:str]
    openai_api_key: ENC[AES256_GCM,data:kwfWixOr2ONhiJHihIjlY3ubpBQTobL4hZyM/4civw+y1uiwn6jmlvGXMq2W+mWNHrd3hhnyCoF+A8rSaVN5V6A0rE0lt/ccv7ka7D+7cSNgB7UQCmfrdakt6/P21BGgV61dhVDT4hmkGlZqCel/rs8XeVGDGjlV4Jj+yzI6RGz7Bu0OH0FEgM0Kyop20Ec=,iv:ul09og2dO+j8K5j7o1ZBsn115Vvj2y0uWJVzp1uJ9fw=,tag:Lv5dy+tCmCapYm2Pjvanrw==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:hIJgICeU4tMTTON9pK3arOddo5s=,iv:lIvng/uHZMLw7p6yX/2eYqEgmbOw/P0QwLnyRO9cfvk=,tag:99eKk7wy3pwREc/znyCgzQ==,type:str]
        port: ENC[AES256_GCM,data:bCu/,iv:br7I3CXemcnCwXg9jU5qoA+oZAw9O7P21e/aTsv0WgQ=,tag:Nu7ilh9iitwmPaEUCQ35Eg==,type:str]
        username: ENC[AES256_GCM,data:TxLIoCKAa0xEsVk4POownsDd5eoASju2657pw8RPtmdNjLYU,iv:7/X4W22j1gQKJDNBmWDjT/TCUvlwzKIS4UYyked/5Go=,tag:JtPERH6kd6MUpygrK9/lMg==,type:str]
        password: ENC[AES256_GCM,data:JrgrGxgL6wDLixUc41bD4kbXde/i68mmCuAK0XmBr+jWKKHV,iv:COmlJdxJ0fOQ01KlL4zUT1N4xKXCrxQx+xLs25B3U+c=,tag:GXpBm1GRb6GmPbGbRysuKg==,type:str]
miniflux:
    client_id: ENC[AES256_GCM,data:gAfIlhWe0+wHflLj/Ei9anqqXvxozL5jeR7o4HQfCOdrrFpnYfhDpQ==,iv:T8Lwb42N993XFHC+ohomXv+dAq9x0Yv8kEtfwNsW+IA=,tag:Q4kVNeIFsj6HN7HgXYNMrg==,type:str]
    client_secret: ENC[AES256_GCM,data:eTDZqyC6RB/3ipVp0/vd8UaNytgApzdobuHpqCFzJfra01mIX6kOnVX+EC2MKftZVsLcClMHIh7sfyWJ+mVv3/G7I+L4rXInCSRxiBbiGn+WLkinCFFsILlY+edu8BOMNOaty1DrBbeDY9BBlfWNuhgf+t/yvD59AQc1ljRAdJM=,iv:Ra4v8M0dC9XFciCe9UNi2EcuwJtZkM5vMAfYhdiK46A=,tag:Bt/Hd5YxlFiR3KvRcoT7nw==,type:str]
users:
    alex: ENC[AES256_GCM,data:5FWXG1nOEcCB1gGBkm/Z69dhhkI/S9iCd8uyywevKSlKcv2O9CFOTmWd6RlcjViRi1/GpQs5hKkFuG+/rwO4xg7mDPuHyhZBsA==,iv:8c6z3yjQgG6FBoDBShdFqreTrrBCnRDC9f5WIxdZgcs=,tag:ciD2ud0WlRSEymvrA4AZPg==,type:str]
vaultwarden:
    admin_token: ENC[AES256_GCM,data:ZMqox3Pu,iv:cLrG1iIAgm6Bl6t0keg/rSpQtipqTed2SIvdccHE1TI=,tag:oZ3FvpawjcNbAfp/kBpOHQ==,type:str]
    push:
        installation_id: ENC[AES256_GCM,data:k8lVYzxRbbvtEesC+gWCchyMnbQkSMj4qY7et1+JjjqNw/19,iv:3Mb2IqBNhUnijTvYChWpqBXhDLY6S17bNutOmLv7BMg=,tag:th/Xgbiy6AwVOPVOA8z0Aw==,type:str]
        installation_key: ENC[AES256_GCM,data:q/4gb4/zu/q/tAzJnL1eAyHQl+U=,iv:abim1KZxr2/nwOhp4ipG7OfX+4P4bGHxhBfxBVQOX4c=,tag:QfXHYLZOwL7DLgza8Sxf3w==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:kJq3YewfUE7nwZ7/Fh0GV/XRBwU=,iv:GKJGJCBqRXW8QInCy2ZB4hXhMk4kJbXgXvuGNuK+BRI=,tag:kIY42IAJpwabLi7lV026ZA==,type:str]
        port: ENC[AES256_GCM,data:2K21,iv:yXOyfl040S50P8xPnfFGHlGqhOsgBxlU17Vi+XegagA=,tag:pvVYEOE/LFMTdBGKNBISIg==,type:str]
        username: ENC[AES256_GCM,data:vdfJy+XDK2rl1IYSay7a8kvT28wgx2IBovqnLAnG1yqdoeIO,iv:e7A5lEqjQ9ACsTPDIto0sb7kZuRUhKaPCCAV1lheVe4=,tag:TMNQ2U9La/ctkNF7KEaJkw==,type:str]
        password: ENC[AES256_GCM,data:T5W3gow/1okHfS91joANXcytY9y1tOUmdXP4hkcAVgLYjOdx,iv:H+/7eUtet9Nektz+d/FA9kMIkERbkKo/A0zgHRplbpk=,tag:OPKNQyB2Ksutn2hFCczFLw==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:KBNz45XU/TY+1mZhzjPIdLxMGxaGCVFLL+RIRTbLH2EgQ+DIEB65/n2Hcw4lQRHljBG6CEite0H4Iz35xDs=,iv:fjyyt3u6OASIrzc+vrf+fLuTt6rlmarr77k553+Z13g=,tag:MLoz8OnVMSY+FZK52BBIgw==,type:str]
vpn:
    private_key: ENC[AES256_GCM,data:oVglqsz/MUge6mQ9DrraXnxuU9/U5FzatRoJMKLLBd4Y0W+QGEoaQaQWaUg=,iv:RPArRJe7ix+u5vti0l2S/KZw5oS9q+eNsZK5pKsSAD0=,tag:r5NJ73CQCDDevUuBmzn3iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcFlaeXR1NVZsWGsvNVF6
            dU95ays2MkltWG9WRERqdTV2S1g0ejVoTkJBCnVvcEc0K2FHWUhZSFpOZFdTUlJG
            Wmw2eG51NFhuN20vRk1kVUo5YWVRWUEKLS0tIER3NkR0ZDFLbWpmMnFrbHNtTjgr
            UGhsRi9GTENjT3FWaHFlQjVSMWhNNGsK4Wpn+eUXBFwia+ovG0zJam1tHkEVHJo7
            sDEKrRiuoV9NWD0042ViGG1NWgm5ZCtZUjqaS4ufh5f//AXiF/18lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ug6lkhhf6svlqskahna8fwxh9rmkz6gkmvjhd55elaalwzp7gtq37k5rr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL21LQytkTnRmaWRjc0g0
            YWtRSXV3aTY2ejIzNFhjaVNUazdBWGJDTHlBCm5mTjNjNGh5OTMxU3NpZ0NvNHN1
            cTg1VnN2VVNtUHlEMXVHNHUza2Jud2sKLS0tIHQwdmYvUzRLT1J1a3RXb1I1b3Mv
            WDcybEU5L3RpK3pPQWhwSWN3STJiSUUKREGIiy0rYabeILe9D7EnJpiSf5NcLjIm
            J2T0SbeSnpMvP/FXsdMHJWzV/xqLjonHKZvxRjPNOqo+UqtYwrEEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T05:20:14Z"
    mac: ENC[AES256_GCM,data:l+iYirQaLeAS4W+e3BbBDEBmLbQuboJmul2iRJq2FmW+EiKV6FwZDSM+14f3hn+nN2pFP2d0z6BDJIb51F0KI11oQZ/bvVop676fzLqYQeEY0C7yU6a4HY5F5Xu11cwd/fgMb30wyzmGXh2JMOZsOz/X0jpK2kc0jnVSYr3TyBE=,iv:jbLe7ZsBLL7BscqSjl//3pQCghKxLE02D/TM9H2CA4g=,tag:C0Bwpk6z9mBOUlcTY/XjBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
