users:
    alex: ENC[AES256_GCM,data:V/4jc7w3U241h24+rKcdGV7FFWpz1ShDIPKE61GagUeG74MFhhMv9RCT15XyuTfxCs2trn7CTb0rnhJJnZaFGTer7Z5cDMwGIA==,iv:+Gur34hJVIcsAb8z9JgSg/uOpt1Qae2KO7YXbAH5SXk=,tag:ckBwkXkLNoWpVauoA9w1bw==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:h9hDPOwBDdLWlZ6wF+lQm5YH1g4tAIsBXI8sgXidXed6TBfWiE5lljpz6OmRm+8UrOf+vdNxBmvmMwEe04I=,iv:pexyWzLX4NL2ktfMfk9wMO5+j2yPxRf+mrXMyQD7xro=,tag:LiNq5TGWgpn9J1ARArLgQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0NGeWJSRDd1U2VHbEpw
            K25tMVoxMkNkVTFOUml3TlFJa09yeDlPR2dJCnIxamN4d25VM0xyUXIyVERlRW43
            ZlluQ2J0TGZkaWo4WTN4Y3ZYbXo1YzQKLS0tIHlpVk9vdXpiMFNkb09Eb1NHbVhV
            RkI3V2IxNjBwSXVXQmcyWlNhdCsydWMKaXicG+t3RjFQbPG1rjZ/IMPBR2sTH2SS
            XR7Z6VMf20qJp+wyDOMWIdRy4Y7WNtK0t4e9fLwjvHBTDKqE7SvYQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14lxusst53pq0qrcwfntmpdpw632sztgkxmw93eqyta82u7tdt3zsxx7ens
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFKzZUbHdNN0kwSzNzYmlv
            WXk2dmNEdDNHNDJyV0QybnFRNURTd1VNVFRRCjhGdWMxQ0VIR2tKWWROcEFpZVF5
            RFRQS3dPZlFnK3BhOUY2Q1hpa1JYZFkKLS0tIFRoUHBQZjJjNm44ZFlNQ0dRZkNa
            MitvK1NTd3N2anluS1BYRFdhK2F4RHcKwntx940IkU/+PUyaATFkTcLF4R2W6wXY
            kD1lCdviYFMOgYi+qksM6Uh98B9Ul92BJGajTpvcFkqPLyg3BHmHeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T06:36:21Z"
    mac: ENC[AES256_GCM,data:OeUQc7qSDrbtKDb/XiuAJ5FfF7KLp5j4LP7YR2rDazkxkGxQNCWs96ZX5fBM0fTEkteAlJ3WKDdqisaMXASTaLBPwYm5216m62Hru5OM3nVSXnZMo/MERJevSgKQifhJz8dKQZzoU7AIZMmjNNsuoFGon7dQRU3pbSYADXUY5k0=,iv:XGVlGV7ajzmocTJ0Ajc3M58GiO8HmSLsC9ouj0Qxp60=,tag:hmT2ocfv0/waW5CnXluJjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
