acme:
    zone_api_token: ENC[AES256_GCM,data:W9IDds0IOYkcGbjCBLoxcaUWAq26zhLUjZkcRKlRGt5bZvX5Fv95Ww==,iv:hzOE8rm9aL/I7f6RcdovacY1tB/OBEOt3ZiJhnBs59E=,tag:Gv4jGFF40ePaJHJVPpIEoA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:F+Cv/QGM/hnwyQ04ygIWu2voP1MVp4z+kcV3K097MJKNBkZD1CtHrg==,iv:cBKw1ndfittwUkUsLH3cl024K2SGhlLOt0ZmYYzG9vU=,tag:U9cf65bPc5Y8p2TWYtbAAw==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:BXOc9wEfqZQM9ThnrdCTA0+iqzjgtBoRc36KrXNel4ld0B4aGxUAyKMXvuwkOS0GSpwTFd/r6fGoPhLkkGC9Vg==,iv:Z+F2v29QIFSjyunIzIL6XLD0m1RlyihYu8c8w+bhN0k=,tag:pbdaEBxOEV7hQ0QtUh6ohQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:mlMHz9FLMp47TLtpZQq19K5zpQM=,iv:CfBR5hisyFDVPMNOWIEjBCanEY548z69OWfiRPoAKZM=,tag:o8zvcmqpbNqsMl72w/290A==,type:str]
        port: ENC[AES256_GCM,data:A7l7,iv:rkcBzsFer2zrFeLhVZIaLPrTbyf8Y8HU4KtLXjTXIqo=,tag:PUOkWcK51uscu3fQU9dArg==,type:str]
        username: ENC[AES256_GCM,data:m6vI9k6Zik+eEgDJTGP6RPf08P1ud/fqKZuvTPxpSJOjqUHU,iv:OhAHjGeHRz0um2JgfrwuGUE0M3DNoVtVCr68dt4Mfa4=,tag:0y2W5x2MYlr3g92k4jM9RQ==,type:str]
        password: ENC[AES256_GCM,data:igM1UbahK1yrT3mx45VFyCWxrynqRT8hzGl+oAGg9yKkW3Pd,iv:rjJEUtptyCQjtI+q0w1Ua5dnwih325IsvZRVp8OLqOQ=,tag:MuXf1xuleW+N3vPLtO21CA==,type:str]
users:
    alex: ENC[AES256_GCM,data:V/4jc7w3U241h24+rKcdGV7FFWpz1ShDIPKE61GagUeG74MFhhMv9RCT15XyuTfxCs2trn7CTb0rnhJJnZaFGTer7Z5cDMwGIA==,iv:+Gur34hJVIcsAb8z9JgSg/uOpt1Qae2KO7YXbAH5SXk=,tag:ckBwkXkLNoWpVauoA9w1bw==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:h9hDPOwBDdLWlZ6wF+lQm5YH1g4tAIsBXI8sgXidXed6TBfWiE5lljpz6OmRm+8UrOf+vdNxBmvmMwEe04I=,iv:pexyWzLX4NL2ktfMfk9wMO5+j2yPxRf+mrXMyQD7xro=,tag:LiNq5TGWgpn9J1ARArLgQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUXJCL08xWGNDK3JtaWJM
            YVo1K1JkVTJCTENHTlF6aXFsY3N6TDB6cHhVCmhVVTg1NGZ2QlphSDdXWllVMFha
            UGFzWmNEVjAvNVZMZWF6WEs0UnVsbDAKLS0tIGlMdHRITUZSRVNONVV5TTQ1aDV2
            VlhPVmZlU3BMRDZYb2hFbkYrd0VIN28KfbnECgPN7xhCm3cV7Avqne8Zke77PtSm
            n6Tp+0ov5Ev1bajwsIuYU/Zqb5BKihz1Us6Iod/+JcI13hfkIEwWzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gtcm2cqy74rh0tsn0jql00try0etqskllnrguhdhmlp6uyynhvhq3tjh42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaFFsU09ZNy9MbTFxMXNo
            a2JTbmZaUnJ2MnhuZy9jSW56QzdHT3lDL0g0CjBYdkEyMUFWd0hNYjc3ODFRUjMr
            VGM1ckhhYnpLM2hnaDl5UzJXZkRGQVEKLS0tIDdhZ3RwaUFPYmwwaHVRRURxZGNR
            RS91TEpyU3JZSzVGbC9OY1g2NzVpNVUKfJ4TfraPmnMq4tRdPNri7MJunY+aIy0A
            BQDpVtqgMS2EMm3WIG1Ol13T40m/mJ3wfa4kFSxKAi5cgAteUbQX4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T20:19:20Z"
    mac: ENC[AES256_GCM,data:m1tAvIuSllvRlTFhKozgx0fwUsBRam9JZ8ER+DeNBmJQ4HsEl2lvdPBVhkTvo+DNfQECAe3cge87d8xGtrJ+JnPKs1eY7cbor/74+Q/tHOkaCrjcs3UCSkm1X40+Y2dKJrlDc8m1vUDfuGoAWwlAfVDw88C7E+skOuJfz6il9iM=,iv:8u8fm1/ViJbRjr//xE/z11yF2ZNLO0ypkOF6677MBzs=,tag:3t/sl9gfs1G8sZckfarvvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
