acme:
    zone_api_token: ENC[AES256_GCM,data:W9IDds0IOYkcGbjCBLoxcaUWAq26zhLUjZkcRKlRGt5bZvX5Fv95Ww==,iv:hzOE8rm9aL/I7f6RcdovacY1tB/OBEOt3ZiJhnBs59E=,tag:Gv4jGFF40ePaJHJVPpIEoA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:F+Cv/QGM/hnwyQ04ygIWu2voP1MVp4z+kcV3K097MJKNBkZD1CtHrg==,iv:cBKw1ndfittwUkUsLH3cl024K2SGhlLOt0ZmYYzG9vU=,tag:U9cf65bPc5Y8p2TWYtbAAw==,type:str]
authentik:
    secret_key: ENC[AES256_GCM,data:BXOc9wEfqZQM9ThnrdCTA0+iqzjgtBoRc36KrXNel4ld0B4aGxUAyKMXvuwkOS0GSpwTFd/r6fGoPhLkkGC9Vg==,iv:Z+F2v29QIFSjyunIzIL6XLD0m1RlyihYu8c8w+bhN0k=,tag:pbdaEBxOEV7hQ0QtUh6ohQ==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:mlMHz9FLMp47TLtpZQq19K5zpQM=,iv:CfBR5hisyFDVPMNOWIEjBCanEY548z69OWfiRPoAKZM=,tag:o8zvcmqpbNqsMl72w/290A==,type:str]
        port: ENC[AES256_GCM,data:A7l7,iv:rkcBzsFer2zrFeLhVZIaLPrTbyf8Y8HU4KtLXjTXIqo=,tag:PUOkWcK51uscu3fQU9dArg==,type:str]
        username: ENC[AES256_GCM,data:m6vI9k6Zik+eEgDJTGP6RPf08P1ud/fqKZuvTPxpSJOjqUHU,iv:OhAHjGeHRz0um2JgfrwuGUE0M3DNoVtVCr68dt4Mfa4=,tag:0y2W5x2MYlr3g92k4jM9RQ==,type:str]
        password: ENC[AES256_GCM,data:igM1UbahK1yrT3mx45VFyCWxrynqRT8hzGl+oAGg9yKkW3Pd,iv:rjJEUtptyCQjtI+q0w1Ua5dnwih325IsvZRVp8OLqOQ=,tag:MuXf1xuleW+N3vPLtO21CA==,type:str]
geoip:
    license_key: ENC[AES256_GCM,data:8ubvLJbrNg/qj4psW87Pp3qxCuhFp7DBfHqGnXr8HvkjPj7zJ0Y7Ug==,iv:chJGyKhEKW04jmyu/I8rvIRuy7kSTNssUkEqbFHLFl4=,tag:j+u7ODX/8afHuMUDbkhHUA==,type:str]
users:
    alex: ENC[AES256_GCM,data:V/4jc7w3U241h24+rKcdGV7FFWpz1ShDIPKE61GagUeG74MFhhMv9RCT15XyuTfxCs2trn7CTb0rnhJJnZaFGTer7Z5cDMwGIA==,iv:+Gur34hJVIcsAb8z9JgSg/uOpt1Qae2KO7YXbAH5SXk=,tag:ckBwkXkLNoWpVauoA9w1bw==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:CGL9iOVRPvSyO1Nl40OVXGYAoJn631mPzxmGCWa6Ytc5qDsPRirSmvuIKXTdFY3AIl6gw9paniuMpxBnYw==,iv:EfwDlEdUrsjg5IZznKz72mFfBt9AaYfCAsh+mOUJ4G8=,tag:1NXL1nvcNz9Ix5craHF0cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUXJCL08xWGNDK3JtaWJM
            YVo1K1JkVTJCTENHTlF6aXFsY3N6TDB6cHhVCmhVVTg1NGZ2QlphSDdXWllVMFha
            UGFzWmNEVjAvNVZMZWF6WEs0UnVsbDAKLS0tIGlMdHRITUZSRVNONVV5TTQ1aDV2
            VlhPVmZlU3BMRDZYb2hFbkYrd0VIN28KfbnECgPN7xhCm3cV7Avqne8Zke77PtSm
            n6Tp+0ov5Ev1bajwsIuYU/Zqb5BKihz1Us6Iod/+JcI13hfkIEwWzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gtcm2cqy74rh0tsn0jql00try0etqskllnrguhdhmlp6uyynhvhq3tjh42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaFFsU09ZNy9MbTFxMXNo
            a2JTbmZaUnJ2MnhuZy9jSW56QzdHT3lDL0g0CjBYdkEyMUFWd0hNYjc3ODFRUjMr
            VGM1ckhhYnpLM2hnaDl5UzJXZkRGQVEKLS0tIDdhZ3RwaUFPYmwwaHVRRURxZGNR
            RS91TEpyU3JZSzVGbC9OY1g2NzVpNVUKfJ4TfraPmnMq4tRdPNri7MJunY+aIy0A
            BQDpVtqgMS2EMm3WIG1Ol13T40m/mJ3wfa4kFSxKAi5cgAteUbQX4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T07:08:15Z"
    mac: ENC[AES256_GCM,data:e0ZktLbb3Xqj05b9l6Z4kjqkqUgmpdNsYl9xAsPvUnP0QMU9FOGcPLroH6wevZy/rGndd/UZD2ei/p1vIe8+L/IDY7L4SJf/CPmjwPTdVmbqjSrSVMR1TC4U38swNUTxmzXfTGtHIeqfJUZUbuq9iP3G+JLaaZT6k8VKHAWg20Y=,iv:umIzxNP7UtBiRT9S0ugmUPRf0rlGFATLhfyNxfPbTQA=,tag:qVSzzX3X3nO2ZLWh5r+czQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
