tailscale:
    key: ENC[AES256_GCM,data:GEps5A8v4ogNqJINYGFaPMOdDD2XEBi1eEx3zsIBcrnI0cNGTxi8qzz4MQ5QvWtJTT5xNV2Wfr61Jr6kBw==,iv:/G70o4Pu87X6C4gX+TKpxBPUUK7ukPpvVuLd1jsLyrc=,tag:6LNTAx+x+xxzDzEy15s/mw==,type:str]
users:
    alex: ENC[AES256_GCM,data:2oDYLbP8MHOSpFT/JoxcbiS+JxtyCV/Rs3Bkky66lzGrhl5HZ0OaN3bg8YPZ5KKXSBZPQaf9TNbUD5s5oDWDQhWgme4W3c1lqQ==,iv:1G4CZ8Yx/jTth/+AV81xsFIN38wgJX4pHzvmbeSLjGc=,tag:Hw90LrbSNBVKTf1I5TjtUw==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbmVpb0ZvRi9DT25zWitH
            Y09RYVhHQTVETFNaQjlKZ1JVNURlSzk0aVcwCk1NbFhDWDA3UWQxWkJxTmFLSlhT
            bnJNbUI3OXA0S1FXSXRReUpzdnhOSDQKLS0tIHVUNVVlbGNhSUg4R3pHZ2o1Y2V2
            dTF1QVlscVlTbzY1YXEzQzhCcDRqV28KTV3KL3tCE+4sW/qpFBZjCwWL+vdn81E9
            /UHBIQ5h2vI2yh8Rskhqxdubd4iqVump1HpMkKX0ObOuhjN88d0UZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10cx6mte5x3np0v8lspatuhfqau8wgpeua532y9zgxy9n4yzpxd7sk2l766
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaEs3VTRwVXh2VmJNcit6
            dzJxbHVGRTBIcExTcmpNZ3g4ZzhqK1BXSVJNCjFmekhhVGtwTGQ5TzNreElSelV0
            VVoyOTZIN29tNFFEcnYwTDg0Z0RNN0UKLS0tIFByVys5TnY3aFBueGtvUFgzQnAw
            aTdlTFpJMktacVJqdlgreVR5MGJoQ1EK03Y7iF+gtXiyTlVJfE0HL9V8hXOf1fCM
            TaGK5d3EF8szuPNaU9Wujt/S4CLNOCPqvnm6RSaHRbTitHN+wN/U6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T02:15:05Z"
    mac: ENC[AES256_GCM,data:GJ62s3sTnm4fqqhCebq29LCjCk1RwzQphXkw4OyaP3i5w8c/U3OQT8kkoIjhzGTIdezd5jrgyKBNr2GO29lVEAZiRSaTLfroWTA3ivGs5IXLREM3euVUZ326f/kmmUtR8/7VHJ0MvTizvr9k5CX8f6XITiMwHw81QXgebQW3s9Y=,iv:6FG5nXv5D48xbtrue3e3tqrRn86PTUpaobSp39JEgnQ=,tag:IahAj6WCSTNB8bBo1hJMjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
