acme:
    zone_api_token: ENC[AES256_GCM,data:i0lV7bMTHhgBvR3i+OhYkt23vXdHAyYx9QxKVjuj/79XA+1ySO8+IRH+658PZTUDi6R81wQ=,iv:/Lh5yDlsCVCDQyK9ZQYUU4VUsoCC6lzNwkFnV0GxfIg=,tag:eknl/vOoaioyERRPCJ9aeA==,type:str]
    dns_api_token: ENC[AES256_GCM,data:Ny4LyR22/spshP6fgu+wdWGTLfniTkv1JGgEf87GhCgQsPE23GWhQ3IDybqm2tbMgzf9AhA=,iv:/GHYJteIVyLFVNAePAqzVnZTLzgcFZic52BReMZZh2E=,tag:C/R3mSSUBY0s0S+EHNAu0g==,type:str]
backblaze:
    backups:
        id: ENC[AES256_GCM,data:GoAgbz8mnjGioL9io8vI48USnoHsBfA+sw==,iv:vmPFhAjA/tnHx7GsnT0PLlxHvQwuIFjpCtfKSiMcJl8=,tag:yoNuItHWR/Vxdcym/YVQkg==,type:str]
        key: ENC[AES256_GCM,data:VsbKi+eYYE3RXb/aOKFVtiVeeu7WIHixAZf/dF3WDA==,iv:x6GjVxrMCidcsfo78DSnFpB5nqnh0Qz3vOsx7aZiLE0=,tag:X8lfukUv/RALyu2VBt6eTQ==,type:str]
git:
    smtp:
        host: ENC[AES256_GCM,data:RWN7wwyXMLmHhhMp/+B1ompyDGQ=,iv:ca+er74Dzx/KffEBtAFrH2i1BbrcrJo2J/MVXgCPobA=,tag:emeMa6+b1rDnNLgo+q+ulw==,type:str]
        port: ENC[AES256_GCM,data:nJ6U,iv:tBkgCE6u3DrBcHS2vn24UmKAzQ63hGtdyCT8ZBguXx8=,tag:PKcY/4+3oYlYThyWTPvfJA==,type:str]
        username: ENC[AES256_GCM,data:wmliuoILxaOMyzrlnNuq/EXO4XVZ81QrE92HlIoNW9BrARc3,iv:4ICR7EFVAu4iP3DsHmMEbI+tc7wkyR8P67AGvOm6hE0=,tag:EfPFc8QAxDjDq5wA0xBc/Q==,type:str]
        password: ENC[AES256_GCM,data:HFh+QQ4OClbjFXb/qfi65BF+086+NCYmcue1EU7P+DUoS2q1,iv:ypZYQgxVWvXZoEmP2sRR1J+gpheQCFXT5AuJ+a2q5m4=,tag:gweCXs2Xya+uUWQ8XBnBDw==,type:str]
tailscale:
    key: ENC[AES256_GCM,data:GEps5A8v4ogNqJINYGFaPMOdDD2XEBi1eEx3zsIBcrnI0cNGTxi8qzz4MQ5QvWtJTT5xNV2Wfr61Jr6kBw==,iv:/G70o4Pu87X6C4gX+TKpxBPUUK7ukPpvVuLd1jsLyrc=,tag:6LNTAx+x+xxzDzEy15s/mw==,type:str]
users:
    alex: ENC[AES256_GCM,data:2oDYLbP8MHOSpFT/JoxcbiS+JxtyCV/Rs3Bkky66lzGrhl5HZ0OaN3bg8YPZ5KKXSBZPQaf9TNbUD5s5oDWDQhWgme4W3c1lqQ==,iv:1G4CZ8Yx/jTth/+AV81xsFIN38wgJX4pHzvmbeSLjGc=,tag:Hw90LrbSNBVKTf1I5TjtUw==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbmVpb0ZvRi9DT25zWitH
            Y09RYVhHQTVETFNaQjlKZ1JVNURlSzk0aVcwCk1NbFhDWDA3UWQxWkJxTmFLSlhT
            bnJNbUI3OXA0S1FXSXRReUpzdnhOSDQKLS0tIHVUNVVlbGNhSUg4R3pHZ2o1Y2V2
            dTF1QVlscVlTbzY1YXEzQzhCcDRqV28KTV3KL3tCE+4sW/qpFBZjCwWL+vdn81E9
            /UHBIQ5h2vI2yh8Rskhqxdubd4iqVump1HpMkKX0ObOuhjN88d0UZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10cx6mte5x3np0v8lspatuhfqau8wgpeua532y9zgxy9n4yzpxd7sk2l766
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaEs3VTRwVXh2VmJNcit6
            dzJxbHVGRTBIcExTcmpNZ3g4ZzhqK1BXSVJNCjFmekhhVGtwTGQ5TzNreElSelV0
            VVoyOTZIN29tNFFEcnYwTDg0Z0RNN0UKLS0tIFByVys5TnY3aFBueGtvUFgzQnAw
            aTdlTFpJMktacVJqdlgreVR5MGJoQ1EK03Y7iF+gtXiyTlVJfE0HL9V8hXOf1fCM
            TaGK5d3EF8szuPNaU9Wujt/S4CLNOCPqvnm6RSaHRbTitHN+wN/U6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T21:36:50Z"
    mac: ENC[AES256_GCM,data:jtBYxnxAcsHLoWyYHNzDaNkeDkrGvvWWt5k9pstoV78pNsFC7FNlHAmHbr78sW/U9ZK0MzomkG9pRHG2uE507+MsFa1UrZFtz34WqLh5pMFTOmChjhqOmab2yo1Kda6HIrvY6odsBH97iXw3oc9YzGTuwHg9xsDKd3Se+XGAt/E=,iv:UfgAnyrePaOUOcLRNxcSXVD8ktYTv/RNoHwLf1K6p2Y=,tag:6/Awqa6opb9L2cIDpgV4/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
