tailscale:
    key: ENC[AES256_GCM,data:GEps5A8v4ogNqJINYGFaPMOdDD2XEBi1eEx3zsIBcrnI0cNGTxi8qzz4MQ5QvWtJTT5xNV2Wfr61Jr6kBw==,iv:/G70o4Pu87X6C4gX+TKpxBPUUK7ukPpvVuLd1jsLyrc=,tag:6LNTAx+x+xxzDzEy15s/mw==,type:str]
users:
    alex: ENC[AES256_GCM,data:ntCiwfPHsMxPqa5bYw08hF+VnIA9yk5xjf7yOtZY5J00zG9Qdp02LuvmJJ5XLKvGkEbmFX038sFZ8zVekZZVPjtiuk8aceOuqg==,iv:weVRdtXJ+sVJ991Sz+WodEzs4DMdVCl1rlgZQv0Y4fI=,tag:SkhhN6Wo6BoLVAi1HX10eQ==,type:str]
sops:
    age:
        - recipient: age18f7dxgrjc2zza2gxc3aek4x4c7u5n8wmh5473m23fza0x56ruyhqeus0d9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QmNzSDQ4WnpTWjAzYVNn
            b0VPbityRG9kdk5CQ0JiVXIzdXRta1FmWGtnCnhQdjlvTGRaWVpQZzNpaTJ0L2tw
            SUQ0ekRrRDJiQ01GU0NoSGk1S1VReTgKLS0tIDZpazlaZEVURy8yT0ZqejB2aFlI
            MXpSU0NFSGt1c3ZMYlNFNnUwcGJxMlkK+Y5wOKsczuancxQ+dMCtzVU2i2oLVdDP
            zdt6hgWDQgvAAzPsqBwd0DpchUvdUFnOt5mXPRPJfH4fiMGP0oTczQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T01:10:39Z"
    mac: ENC[AES256_GCM,data:oOU8erRdJyJsu9pm5JF5BmNFlblHtCgn459TKcSFjT3R1ydrcgdg3FRFnFFSoBb1LCr56kc/7ChZM8XQjowPcdGNROoB/dbz6mCAFLyZtIGTDiCG2DRGDNdZU9VSeiXdekLwyGotMp8plOJ/zZu73ek1LZgW8ufvrsMMvu40ZBo=,iv:/xC4u76eG1z5vYvKL5Y6bNRF1u3S9Hs5XNCDDVDYxkk=,tag:2Jn159EB7EUsLwlxAUyTug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
