---
# yamllint disable-line rule:truthy
on: push

name: Deploy

env:
  OPENTOFU_VERSION: 1.6.2
  TERRAGRUNT_VERSION: 0.56.5
  WORKING_DIRECTORY: terraform

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.event_name }}-${{ github.run_id }}-${{ github.job }}
          aws-region: ca-central-1

      - uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.OPENTOFU_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.WORKING_DIRECTORY }}
          tg_command: run-all plan

  apply:
    name: Apply
    needs:
      - plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.event_name }}-${{ github.run_id }}-${{ github.job }}
          aws-region: ca-central-1

      - uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.OPENTOFU_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.WORKING_DIRECTORY }}
          tg_command: run-all apply
