on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v3
      - uses: hashicorp/setup-terraform@v2
      
      - run: just init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: just ci
