---
# yamllint disable-line rule:truthy
on: push

name: Lint

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: Install Terragrunt
        run: |
          url=$(gh release view --repo gruntwork-io/terragrunt --json assets --jq '.assets[] | select(.name | endswith("linux_amd64")) | .url')
          wget -qO terragrunt $url
          chmod +x terragrunt
        env:
          GH_TOKEN: ${{ github.token }}

      - run: just terraform/ init ci

  yaml:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install yamllint
      - run: yamllint -s -f github .
