---
# yamllint disable-line rule:truthy
on: push

name: Lint

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v4
      - uses: hashicorp/setup-terraform@v3

      - run: just init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - run: just ci

  yaml:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install yamllint
      - run: yamllint -s -f github .
