---
"on": push

name: Lint

env:
  # renovate: datasource=github-releases packageName=opentofu/opentofu
  OPENTOFU_VERSION: 1.8.3
  # renovate: datasource=github-releases packageName=gruntwork-io/terragrunt
  TERRAGRUNT_VERSION: v0.67.10

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just
      - uses: terraform-linters/setup-tflint@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.OPENTOFU_VERSION}}
          tofu_wrapper: false
      - name: Install Terragrunt
        run: |
          url=$(gh release view ${{ env.TERRAGRUNT_VERSION }} --repo gruntwork-io/terragrunt --json assets --jq '.assets[] | select(.name | endswith("linux_amd64")) | .url')
          wget -qO terragrunt $url
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.event_name }}-${{ github.run_id }}-${{ github.job }}
          aws-region: ca-central-1

      - run: just terraform/ init ci

  yaml:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install yamllint
      - run: yamllint -s -f github .
