---
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'Tag to build'

name: ntfy

jobs:
  android:
    name: Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: binwiederhier/ntfy-android
          ref: ${{ github.event.inputs.tag }}

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Import Google services file
        run: echo "$GOOGLE_SERVICES" > app/google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Import signing keystore
        run: echo "$APK_RELEASE_KEYSTORE" | base64 -d > release.jks
        env:
          APK_RELEASE_KEYSTORE: ${{ secrets.APK_RELEASE_KEYSTORE }}

      - name: Update server URL
        run: sed -i "s|https://ntfy.sh|https://notify.krantz.cloud|g" app/src/main/res/values/values.xml

      - name: Build
        run: ./gradlew assemblePlayRelease

      - name: Sign
        run: |
          zipalign -v -p 4 app/build/outputs/apk/play/release/app-play-release-unsigned.apk app/build/outputs/apk/play/release/app-play-release-unsigned-aligned.apk
          apksigner sign --ks release.jks --ks-pass "pass:$STORE_PASSWORD" --ks-key-alias ntfy --out app/build/outputs/apk/play/release/app-play-release.apk app/build/outputs/apk/play/release/app-play-release-unsigned-aligned.apk
          apksigner verify app/build/outputs/apk/play/release/app-play-release.apk
        env:
          STORE_PASSWORD: ${{ secrets.APK_RELEASE_KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: ntfy.apk
          path: app/build/outputs/apk/play/release/app-play-release.apk
          if-no-files-found: error
