---
name: Coder

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/workflows/templates.yml
      - templates/**

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.generator.outputs.templates }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          templates=$(/bin/ls templates | jq -Rcs 'split("\n")[:-1]')
          echo "templates=$templates" >> "$GITHUB_OUTPUT"
        id: generator

  publish:
    name: Publish Template
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    strategy:
      matrix:
        template: ${{ fromJSON(needs.generate-matrix.outputs.templates) }}
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Install Coder CLI
        run: curl -L https://coder.com/install.sh | sh

      - name: Get short commit SHA
        run: echo "short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        id: sha

      - name: Push templates
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: coder templates push $CODER_TEMPLATE_NAME --directory $CODER_TEMPLATE_DIRECTORY --yes --name $CODER_TEMPLATE_VERSION
        env:
          CODER_URL: https://code.krantz.dev
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
          CODER_TEMPLATE_NAME: ${{ matrix.template }}
          CODER_TEMPLATE_VERSION: ${{ steps.sha.outputs.short }}
          CODER_TEMPLATE_DIRECTORY: ./templates/${{ matrix.template }}
